@echo off
echo Day la file tu dong cap nhat cac thay doi moi nhat len GitHub.
echo Dang vao thu muc...
cd /d C:\Users\as\.gemini\antigravity\scratch\rennphim
echo Dang cau hinh Git...
git config user.email "artrenn-sudo@users.noreply.github.com"
git config user.name "artrenn-sudo"
echo Dang staging cac file...
git add .
echo Dang commit cac thay doi...
git commit -m "UX Refinements: Search fix, Auto-Next/Skip Intro timing, Ad-blocking, and Routing"
echo Dang day len GitHub...
git push origin main
echo Mo web link phim de kiem tra ket qua nhe!
echo XONG ROI! Kiem tra GitHub nhe ban!
pause
